### ISSUE TITLE
Proposal: Ignore tests & src from npm package

### ISSUE THREAD

**Issue by zpao** [evcohen/jsx-ast-utils#18]
`src` is compiled away and `__tests__` obviously aren't much use so I recommend ignoring them when publishing. I just saw a diff fly by me where we check in node_modules so figured I'd reach out and see it would be possible to ignore them in the future.

I just did a dry run and it takes ~12kb off the .tgz. Looking at the last month of downloads on npm that saves ~17.5gb of bandwidth 😯

**Comment by IanVS** [comment]
Would the maintainers accept a PR adding development artifacts to the `.npmignore` file?

**Comment by ljharb** [comment]
`npm explore foo && npm install && npm test` should always work; "development artifacts" should be published too.

12K is negligible; "17.5GB per month" is npm's concern, not the concern of package authors.
