### ISSUE TITLE
UpdateExpression unknown

### ISSUE THREAD

**Issue by joscha** [evcohen/jsx-ast-utils#3]
When running eslint over our source, the following error occurs: https://github.com/eslint/eslint/issues/7341

seems as if JSX `UpdateExpression` is unknown by jsx-ast-utils.

**Comment by evcohen** [comment]
[v1.3.2](https://github.com/evcohen/jsx-ast-utils/releases/tag/v1.3.2) published with fix! Thanks for reporting 😄
