### ISSUE TITLE
The template literal for undefined not calculated correctly in props.

### ISSUE THREAD

**Issue by AlmeroSteyn** [evcohen/jsx-ast-utils#40]
Given the following:

```
<a href={`${undefined}`} />
```

In an actual component, this is rendered as:

```
<a href="undefined" />
```

This is the default behaviour for such a template literal in JavaScript.

However in `getPropValue` this is returned as an empty string. 

It seems to be intended behaviour as there is also a test for this:
```
    it('should drop variables in template literals that are literally undefined', () => {
      const prop = extractProp('<div foo={`bar ${undefined}`} />');

      const expected = 'bar ';
      const actual = getPropValue(prop);

      assert.equal(expected, actual);
    });
```

However, the difference between the actual JSX / JavaScript behaviour and the result calculated here can lead to confusion when used in linters and tests.

**Comment by ljharb** [comment]
Specifically:
```js
`${undefined}` === 'undefined'
```

**Comment by evcohen** [comment]
just ran this in node and this is true, but this is unexpected behavior to me...does it just call toString on anything in between the braces?

**Comment by ljharb** [comment]
Yes, that's exactly what it does.
