### ISSUE TITLE
Consider handling typescript-eslint-specific AST

### ISSUE THREAD

**Issue by vhfmag** [evcohen/jsx-ast-utils#71]
The team I work on is migrating a Flow project to Typescript, and we are trying to keep our ESLint setup by using [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint), but things were not working out as expected.

After some debugging, we found out that the issue was within `jsx-ast-utils`, which didn't correctly handle JSX attributes in the form of `atribute={value!}` (where `!` is a Typescript non-null assertion, i.e. it tells Typescript to assume that `value` is neither `null` or `undefined`). It crashed [here](https://github.com/evcohen/jsx-ast-utils/blob/master/src/values/expressions/index.js#L112-L114), more specifically. The issue is that `@typescript-eslint/typescript-estree` exposes it as a `TSNonNullExpression` node with `value`'s AST as `node.expression`.

For our codebase, simply adding
```js
if (type === "TSNonNullExpression") {
  expression = expression.expression;
  type = expression.type;
}
```
before that check made everything work. It's a fairly large React codebase, so I guess it's fair to assume there would be little additional work.

I would be happy to come up with a PR if the project sees this as desirable. Thanks!

**Comment by ljharb** [comment]
Seems desirable to me.

**Comment by vhfmag** [comment]
Just submitted #72 :)
