### ISSUE TITLE
elementType(node) returns "undefined.ComponentName"

### ISSUE THREAD

**Issue by julienben** [evcohen/jsx-ast-utils#9]
Hey Ethan,

Thanks for this great tool!

I'm building an ESLint rule for a project to warn our team when we use <this.ComponentName /> in JSX. (Because JSX tag names should always start with a capital and it sometimes compiles to "(void 0).ComponentName" which obviously won't run.)

However, elementType(node) returns "undefined.ComponentName" in a few cases:
<Component.Child.RenderThisGuy /> becomes "undefined.RenderThisGuy"
<this.props.Component> becomes "undefined.Component"

I can't check for names that start with "undefined" because, as you can see above, the first would be a false positive. And if I check only names that start with "this", I'm missing some instances.

Do you have any idea what could be causing this? And do you need any further info about the code I'm testing?

Thanks for any assistance!

Julien

**Comment by evcohen** [comment]
hey julien - pumped that you're using it! thanks for filing the issue. this is a bug in `elementType`, where we aren't recursively checking for `JSXMemberExpression`s (X.Y) as the element. we just assume that it starts with one (i.e. `<Component.Child />`). Will work on a fix right now!

**Comment by evcohen** [comment]
Fixed in [v1.3.4](https://github.com/evcohen/jsx-ast-utils/releases/tag/1.3.4), thanks for reporting! 😄

**Comment by julienben** [comment]
Thanks so much for your crazy fast response! Shalom from Tel Aviv!

**Comment by evcohen** [comment]
shalom achi 👍
